# Generated by Django 4.0.3 on 2022-04-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0009_recete_toplam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recete',
            name='toplam',
            field=models.FloatField(blank=True, null=True, verbose_name='Tutar (TL)'),
        ),
    ]
